// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxCV0Fx9VrrBnpIzaLQuac3wDBC0n6374',
    appId: '1:767025343690:web:08268922be4fb683131833',
    messagingSenderId: '767025343690',
    projectId: 'crypto-wallet-af463',
    authDomain: 'crypto-wallet-af463.firebaseapp.com',
    storageBucket: 'crypto-wallet-af463.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC55WhzFZjDCFYurWgCmDODscuVEAsdYqM',
    appId: '1:767025343690:android:e5d45a58c5432db5131833',
    messagingSenderId: '767025343690',
    projectId: 'crypto-wallet-af463',
    storageBucket: 'crypto-wallet-af463.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQcwDnwmNQd3TT6NQ0mKjYxT0lE0KImC8',
    appId: '1:767025343690:ios:05c23f039068042a131833',
    messagingSenderId: '767025343690',
    projectId: 'crypto-wallet-af463',
    storageBucket: 'crypto-wallet-af463.appspot.com',
    iosClientId: '767025343690-ia6sr9pbpsiil1bpdu70s787smkpqd1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQcwDnwmNQd3TT6NQ0mKjYxT0lE0KImC8',
    appId: '1:767025343690:ios:05c23f039068042a131833',
    messagingSenderId: '767025343690',
    projectId: 'crypto-wallet-af463',
    storageBucket: 'crypto-wallet-af463.appspot.com',
    iosClientId: '767025343690-ia6sr9pbpsiil1bpdu70s787smkpqd1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinbank',
  );
}
